# Generated by Django 3.0.2 on 2020-02-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('distrito', models.CharField(choices=[('Comas', 'Comas'), ('Los Olivos', 'Los Olivos'), ('San Martín de Porres', 'San Martín de Porres')], max_length=100)),
                ('Teléfono', models.CharField(max_length=20)),
                ('Ubicación', models.CharField(max_length=100)),
                ('Costo por hora', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Jugadores por equipo', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='jugador',
            name='distrito',
            field=models.CharField(choices=[('Comas', 'Comas'), ('Los Olivos', 'Los Olivos'), ('San Martín de Porres', 'San Martín de Porres')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(choices=[('Arco', 'Arco'), ('Defensa', 'Defensa'), ('Mediocampo', 'Mediocampo'), ('Ataque', 'Ataque')], max_length=20),
        ),
    ]
