# Generated by Django 3.0.2 on 2020-02-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200210_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='Jugadores por equipo',
            field=models.IntegerField(),
        ),
    ]
