# Generated by Django 3.0.2 on 2020-02-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20200210_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='hora',
            field=models.TimeField(),
        ),
    ]
