# Generated by Django 3.0.2 on 2020-02-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('nick', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('distrito', models.CharField(max_length=50)),
                ('posicion', models.CharField(choices=[('Arco', 'Arco'), ('Defensa', 'Defensa')], max_length=20)),
                ('descripcion', models.TextField()),
                ('password', models.CharField(max_length=156)),
            ],
        ),
    ]
