# Generated by Django 3.0.2 on 2020-02-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200210_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='descripcion',
            field=models.TextField(default='Juego'),
        ),
        migrations.AddField(
            model_name='juego',
            name='hora',
            field=models.TimeField(auto_now=True),
        ),
    ]
